### ISSUE TITLE
 Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by hqqxxf** [ipikuka/remark-flexible-markers#3] opened 2024-05-31 08:54 UTC
IOS 16 regex bug:
<img width="519" alt="image" src="https://github.com/ipikuka/remark-flexible-markers/assets/11484241/c90ba2fd-1b75-4756-8b11-4dbaae07cea9">

**Comment by talatkuyuk** [comment] 2024-06-01 12:08
Thank you for reporting the issue.

ios 16? which version of **chrome** or **safari** you use in which device? I don't get any error from my safari (v17.5) or chrome (v.125) in my macbook pro.

I tried the regex in https://regex101.com/r/r8zk5N/1 using different flavor, only `rust` and `golang` raised an error, but ECMAScript (js) has no problem with it.

**Comment by hqqxxf** [comment] 2024-06-02 03:57
![image](https://github.com/ipikuka/remark-flexible-markers/assets/11484241/986d005b-3965-4f02-b33c-115ab0051c24)
@talatkuyuk

**Comment by talatkuyuk** [comment] 2024-06-02 09:41
The regex you mentioned in the issue consists **regex lookbehind**.

From https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes
> Added support for RegExp lookbehind assertions.

Regex lookbehind is supported as of safari version 16.4 which needs to have minimum ios 16.4 in your device iphone 13.

So, **I advice you to update ios from 16.2 to 17.5 which is latest in your device.**

Then, let me know if the issue is resolved to close it.

**Comment by talatkuyuk** [comment] 2024-06-29 18:23
Do you plan to close the issue?

**Closed as completed** 2024-09-30 04:45 UTC
